[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/timeactive"
  to = "/timeactive/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/timeactive/"
  to = "/timeactive/index.html"
  status = 200
  force = true
